### PR TITLE
Add sidebar link to Open Collective

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Review by soupault — APPROVED** [review]

**Comment by stefanv** [comment]
Huh, interesting... I tested locally and the Github stars worked just fine, but when I go to scikit-image.org I no longer see it?

**Comment by lagru** [comment]
> Huh, interesting... I tested locally and the Github stars worked just fine, but when I go to scikit-image.org I no longer see it?

Same for me.

**Comment by lagru** [comment]
Using the developer tools it seems to be there

```html
<div style="text-align: center;" width="100%">
  <iframe src="http://ghbtns.com/github-btn.html?user=scikit-image&amp;repo=scikit-image&amp;type=watch&amp;count=true" allowtransparency="true" frameborder="0" scrolling="0" width="110" display="inline-block" height="20"></iframe>
</div>
```

**Comment by soupault** [comment]
Hmm... I do not see it either on the page:
image

However, the widget is shown properly when the link is used directly (http://ghbtns.com/github-btn.html?user=scikit-image&repo=scikit-image&type=watch&count=true).

**Comment by soupault** [comment]
This works (by monkey patching):
```
<iframe src="https://ghbtns.com/github-btn.html?user=scikit-image&repo=scikit-image&type=star&count=true" frameborder="0" scrolling="0" width="110" display="inline-block" height="20"></iframe>
```

**Comment by stefanv** [comment]
@soupault What did you change? Only the transparency bit? I can't get that to work in my developer view.

By the way, I noticed that random.js did not get built for the latest version of the docs, so our random example from the gallery is also failing on the website!

**Comment by soupault** [comment]
@stefanv It seems that switching from `http` to `https` is critical, at least in my environment. Other changes are just to follow the latest template from `ghbtns.com`.

**Pull request merged**
